### ISSUE TITLE
Bug: (rule 'swift_proto_library') doesn't contain declared provider 'CcInfo'

### ISSUE THREAD

**Issue by chiragramani** [MobileNativeFoundation/rules_xcodeproj#2637]
### Description

Project gen fails for us with the following trace:
```
swift_proto_library rule //librariesA:libraryB: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_ios/rules_xcodeproj.noindex/build_output_base/external/rules_xcodeproj/xcodeproj/internal/xcodeproj_aspect.bzl", line 62, column 36, in _xcodeproj_aspect_impl
		info = create_xcodeprojinfo(
	File "/private/var/tmp/_bazel_ios/rules_xcodeproj.noindex/build_output_base/external/rules_xcodeproj/xcodeproj/internal/xcodeprojinfo.bzl", line 652, column 44, in create_xcodeprojinfo
		info_fields = _create_xcodeprojinfo(
	File "/private/var/tmp/_bazel_ios/rules_xcodeproj.noindex/build_output_base/external/rules_xcodeproj/xcodeproj/internal/xcodeprojinfo.bzl", line 514, column 50, in _create_xcodeprojinfo
		processed_target = process_library_target(
	File "/private/var/tmp/_bazel_ios/rules_xcodeproj.noindex/build_output_base/external/rules_xcodeproj/xcodeproj/internal/library_targets.bzl", line 86, column 25, in process_library_target
		cc_info = target[CcInfo],
Error: <target //librariesA:libraryB> (rule 'swift_proto_library') doesn't contain declared provider 'CcInfo'
```

### Reproduction steps

I currently am working on a repro and will share one soon.

### Expected behavior

Project gen should be successful.

### rules_xcodeproj version

1.10.1

### Xcode version

Xcode.15.0.0.15A240d

### Bazel version

6.3.2

### rules_apple version

2.3

### rules_swift version

1.12.0

**Comment by chiragramani** [comment]
@thii would be great to get your input on this issue, thanks!

**Comment by thii** [comment]
A repro would be great. I have yet to figure out why a CcInfo is not there. There should always be one IIUC.

https://github.com/bazelbuild/rules_swift/blob/2713face93b3ed4703d0e2c763bb6fc10336782a/swift/internal/swift_proto_library.bzl#L54-L57

**Comment by chiragramani** [comment]
Upon further examination, I discovered that the issues were not related to `rules_xcodeproj` or `swift_proto_library`. Instead, there was some weird logic on our end that needed adjustment. After addressing that, everything functions as expected. My apologies for raising this issue prematurely.
